game = "connect_four"

[model]
n_resnet_blocks = 2
activation="tanh"
optimizer="adam"
policy_factor=1.0

[save]
save_path = ""
checkpoint_every = 5

[benchmark]
tournament_frequency = 5
n_tournament_games = 10
benchmark_path = ""
n_best_self_games = 10
mcts_bot_iterations = []

[self_play]
n_tree_workers = 2
n_threads = 2
n_workers = 2
evaluator_batch_size = 32
epsilon = 0.25
alpha = 1.0

[[stages]]
n_generations = 1
learning_rate = 0.001
momentum = 0.9
buffer_length = 600000
n_purge = 0
n_simulations_per_move = 5
discount_factor = 0.99
update_epochs = 1
n_games_per_worker = 5
training_samples = 40000
