name: pyoaz
on: 
  push:
    branches: [master, refactor]
  pull_request:
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update pip
        run: python3 -m pip install --upgrade-pip-setuptools
      - name: install requires
        run: python3 -m pip install -r requirements.txt
      - name: run black
        run: python3 -m black --check .