name: Run test suites
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/ameroueh/oaz-cpu-github:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: |
            cmake . -B build -DCMAKE_BUILD_TYPE=Debug && cd build && make -j$(nproc) && ctest
        name: Run C++ test suite
      # - run: |
      #       python setup.py bdist_wheel && cd dist && pip install *.whl && cd ../pyoaz_tests && pytest

            

