name: run test suites
on: 
  push:
    branches:
      - feature/add-testing-workflow
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    container: ghcr.io/ameroueh/oaz-cpu:latest
    steps:
      - run: sudo chown -R $USER:$USER /__w/oaz
      - uses: actions/checkout@v2
      - run: |
             echo "Hello! I am $EUID" 
        name: display user
