name: run test suites
on: 
  push:
    branches:
      - feature/add-testing-workflow
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/ameroueh/oaz-cpu-github:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: |
             echo "Hello!"
             ls
        name: Display working directory
